Added merge mode
trocco-io/embulk-output-bigquery_java pull request #96
Opened 2024-07-17 01:43 UTC by t3t5u

2024-07-17 03:24 UTC, t3t5u commented on src/main/java/org/embulk/output/bigquery_java/BigqueryClient.java
> +        sb.append("MERGE ");
https://cloud.google.com/bigquery/docs/reference/standard-sql/dml-syntax#merge_statement

2024-07-17 03:25 UTC, t3t5u commented on src/main/java/org/embulk/output/bigquery_java/BigqueryClient.java
> +                quoteIdentifier(dataset) + ".INFORMATION_SCHEMA.KEY_COLUMN_USAGE KCU " +
https://cloud.google.com/bigquery/docs/information-schema-key-column-usage

2024-07-17 03:25 UTC, t3t5u commented on src/main/java/org/embulk/output/bigquery_java/BigqueryClient.java
> +                quoteIdentifier(dataset) + ".INFORMATION_SCHEMA.TABLE_CONSTRAINTS TC " +
https://cloud.google.com/bigquery/docs/information-schema-table-constraints

2024-07-17 03:26 UTC, t3t5u commented on src/main/java/org/embulk/output/bigquery_java/BigqueryClient.java
> +        return "`" + identifier + "`";
https://cloud.google.com/bigquery/docs/reference/standard-sql/lexical#quoted_identifiers

2024-07-17 04:04 UTC, t3t5u commented on src/main/java/org/embulk/output/bigquery_java/BigqueryJavaOutputPlugin.java
> +                client.merge(task.getTempTable().get(), task.getTable(), task.getMergeKeys().orElse(Collections.emptyList()), task.getMergeRule().orElse(Collections.emptyList()));
Table copy job can only use `WRITE_TRUNCATE` or `WRITE_APPEND`, so use query job to merge instead.
https://cloud.google.com/bigquery/docs/reference/rest/v2/Job#jobconfigurationtablecopy
https://cloud.google.com/bigquery/docs/reference/rest/v2/Job#jobconfigurationquery

2024-07-17 04:19 UTC, t3t5u commented on src/main/java/org/embulk/output/bigquery_java/BigqueryClient.java
> +        sb.append("MERGE ");
SQL will look like this.
```
MERGE `test_by_sano`.`output` T
USING `test_by_sano`.`LOAD_TEMP_b7c8436b_de2e_458b_8ab0_faf969b1ed9c_output` S
   ON T.`key_long` = S.`key_long`
  AND T.`key_string` = S.`key_string`
 WHEN MATCHED THEN
    UPDATE SET
      T.`key_long` = S.`key_long`,
      T.`key_string` = S.`key_string`,
      T.`test_boolean` = S.`test_boolean`,
      T.`test_long` = S.`test_long`,
      T.`test_double` = S.`test_double`,
      T.`test_string` = S.`test_string`,
      T.`test_timestamp` = S.`test_timestamp`,
      T.`test_json` = S.`test_json`
 WHEN NOT MATCHED THEN
    INSERT (
      `key_long`,
      `key_string`,
      `test_boolean`,
      `test_long`,
      `test_double`,
      `test_string`,
      `test_timestamp`,
      `test_json`)
    VALUES (
      `key_long`,
      `key_string`,
      `test_boolean`,
      `test_long`,
      `test_double`,
      `test_string`,
      `test_timestamp`,
      `test_json`)
```

2024-07-17 11:23 UTC, t3t5u commented on src/main/java/org/embulk/output/bigquery_java/BigqueryClient.java
> +        sb.append("MERGE ");
NOTE:
`MERGE` statement initiates an implicit transaction and are automatically committed.
https://cloud.google.com/bigquery/docs/data-manipulation-language#limitations
```
Each DML statement initiates an implicit transaction,
which means that changes made by the statement are automatically committed at the end of each successful DML statement.
```
https://cloud.google.com/bigquery/docs/transactions#statements_supported_in_transactions
https://cloud.google.com/bigquery/docs/multi-statement-queries#collect_multi_statement_query_info
https://cloud.google.com/bigquery/docs/information-schema-jobs#multi-statement_query_job

2024-07-19 01:57 UTC, t3t5u commented on src/main/java/org/embulk/output/bigquery_java/BigqueryJavaOutputPlugin.java
> +                // TODO: create table to support partition
https://cloud.google.com/bigquery/docs/using-dml-with-partitioned-tables#using_a_merge_statement

2024-07-19 15:57 UTC, t3t5u commented on src/main/java/org/embulk/output/bigquery_java/BigqueryJavaOutputPlugin.java
> +                client.createTableIfNotExist(task.getTable()); // needs for when task['table'] is a partition
https://cloud.google.com/bigquery/docs/using-dml-with-partitioned-tables#using_a_merge_statement

2024-07-22 01:31 UTC, t3t5u commented on src/main/java/org/embulk/output/bigquery_java/BigqueryClient.java
> +                            return bigquery.query(configuration, builder.build());
https://github.com/googleapis/java-bigquery/blob/v2.14.0/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQuery.java#L1588-L1606
```
If the location of the job is not "US" or "EU", the jobId must specify the job location.
```

2024-08-01 07:31 UTC, d-hrs requested changes
please write explanation about `merge_keys` and `merge_ruels` in README.

2024-08-02 04:08 UTC, d-hrs approved these changes
LGTM

2024-08-05 02:42 UTC, NamedPython approved these changes

2024-08-05 02:42 UTC, merged